spring:
  datasource:
    url: ${DATABASE_URL}
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTYzODM3NzMyMSwiaWF0IjoxNjIyNTY2MTIxfQ.Se-3euzeSQNLnrKLv-u8YTXgQUWgm7PonTFwyyUjY_Y
  expiration: 36000
